name = "Allium Season 12"
author = "Devoid_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "327d4541f1330fb84566aead389b9d8c69e08111446c56a01d4d88ec38955c1f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
