name = "Allium Season 12"
author = "Devoid_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61cc6c4ab1aed62c24309d3033a40e9b641948d642821bc611f578f067356a58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
