name = "Allium Season 12"
author = "Devoid_"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "748c180f2ec2372a445da6cbe6af6f09ca1a78e035c5350537181822c10f1bb3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
